service: puppeteer-layer

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-northeast-1
  profile: serverless

layers:
  modules:
    path: modules
    description: modules layer
    compatibleRuntimes:
      - nodejs10.x

resources:
  Outputs:
    ModulesLayerExport:
      Value:
        Ref: ModulesLambdaLayer
      Export:
        Name: ModulesLambdaLayer
