service: crawler-puppeteer

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-northeast-1
  profile: serverless
  timeout: 900
  environment:
    PUPPETEER_LAYER_SERVICE: puppeteer-layer

package:
  exclude:
    - node_modules/**
    - package.json
    - package-lock.json
    - .env
    - .env.example
    - .eslintrc.json

functions:
  crawler:
    handler: handler.crawler
    description: crawler function
    layers:
      - ${cf:${self:provider.environment.PUPPETEER_LAYER_SERVICE}-${opt:stage, self:provider.stage}.ModulesLayerExport}
